services:
  app:
    image: pg-app-project:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: pg-app-project
    ports:
      - "8005:8005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/pg_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: amdin
      SPRING_DATASOURCE_PASSWORD: pg-admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: pg_db
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:  # Named volume for the database
